name: Prod Container Image CI

on:
  push:
    branches: [ "main"]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main

      - name: Docker meta
        id: docker-meta-id # you'll use this in the next step
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/nicenode/benchbuddy
          # Docker tags based on the following events/attributes
          tags: |
            latest
            ${{steps.package-version.outputs.current-version}}
          labels: |
            performance
            testing
            speed
            storage
            disk
            internet
            hardware

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: jgresham
          password: ${{ secrets.GH_PUSH_PACKAGES }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Containerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker-meta-id.outputs.tags }}
          labels: ${{ steps.docker-meta-id.outputs.labels }}
          
    # - uses: actions/checkout@v3
    # - run: |
    #     sudo apt-get update

    # - name: Build the Container image
    #   run: docker buildx build . --platform linux/arm64, linux/amd64 --file Containerfile --tag nicenode/benchbuddy:$(date +%s)
